# Generated by Django 4.2.6 on 2025-02-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0002_produit_user_commande_ajout_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.CharField(max_length=150),
        ),
    ]
