# Generated by Django 4.2.6 on 2025-02-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0003_alter_produit_prix_alter_produit_quantite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ajout_Livraison',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
