# Generated by Django 4.2.6 on 2025-02-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rapido_app', '0004_delete_admin_remove_commande_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=80)),
                ('sexe', models.CharField(max_length=20)),
                ('disponibilite', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=150)),
                ('quantite', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('heure_livraison', models.CharField(max_length=50)),
                ('adresse_livraison', models.TextField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ajout_Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('adresse_livraison', models.TextField()),
                ('statut', models.CharField(default='En cours', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.livreur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.produit')),
            ],
        ),
    ]
