# Generated by Django 4.2.6 on 2025-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='disponibilite',
            field=models.CharField(default='Oui', max_length=20),
        ),
    ]
