# Generated by Django 4.2.6 on 2025-02-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0006_alter_livreur_disponibilite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ajout_Livraison',
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
    ]
