# Generated by Django 4.2.6 on 2025-02-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0007_delete_ajout_livraison_delete_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=80)),
                ('sexe', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disponibilite', models.CharField(default='Oui', max_length=20)),
                ('contact', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ajout_Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('adresse_livraison', models.TextField()),
                ('statut', models.CharField(default='En cours', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.livreur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.produit')),
            ],
        ),
    ]
