# Generated by Django 4.2.6 on 2025-02-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0008_livreur_ajout_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
