# Generated by Django 4.2.6 on 2025-02-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0009_alter_livreur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajout_livraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido_app.admin'),
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
    ]
