# Generated by Django 4.2.6 on 2025-02-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0011_livreur_alter_ajout_livraison_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajout_livraison',
            name='quantite',
        ),
    ]
