# Generated by Django 4.2.6 on 2025-02-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapido_app', '0012_remove_ajout_livraison_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajout_livraison',
            name='adresse_livraison',
        ),
    ]
